- link:
    $HOME/.config/nvim: neovim
- shell:
    -
        description: "[neovim] installing plugins"
        command: |
            bash neovim/plugup.sh || \
            echo '[neovim] could not install plugings completely'
        quiet: true
