#!/bin/sh

here="$(dirname "$0")"
checkcmd() {
  which -s "$@" >/dev/null
  return $?
}

if checkcmd zsh; then
  zsh "$here/bootstrap.sh"
  if [ $? -ne 0 ]; then
    echo "Something went wrong..."
  fi
else
  echo "zsh could not be found. Can not bootstrap."
fi
